# System Configuration
spring:
  application:
    name: jpa-new
  datasource:
    platform: mysql
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mariadb://localhost:3307/springjpa
    driver-class-name: org.mariadb.jdbc.Driver
    username: jpa
    password: jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    show-sql: true
    hibernate:
        ddl-auto: create
        use-new-id-generator-mappings: true
    properties:
        hibernate: 
            use_sql_comments: true
            format_sql: true
  mvc:
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp 
    static-path-pattern: /resources/**