# System Configuration
spring:
  application:
    name: jpa-new
  datasource:
    platform: mysql
    url: jdbc:mariadb://localhost:3307/springjpa
    driver-class-name: org.mariadb.jdbc.Driver
    username: jpa
    password: jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
        ddl-auto: create
    properties:
        hibernate: 
            use_sql_comments: true
            format_sql: true
